[project]
author = "HCA Team"
name = "batmanfromtoml"
url = "https://none"
version = "0.0.1"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project.scripts]
batman-convert = "batman.bat_to_tackle:convert"
batman-hello = "batman.bat_to_tackle:hello"
