[project]
author = "HCA Team"
name = "batmanfromtoml"
url = "https://none"
version = "0.0.1"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project.scripts]
batman-usage = "batman.batman:Batman.usage"
batman-convert = "batman.convert:main"
